### ISSUE TITLE
Just an idea about scopes

### ISSUE THREAD

**Issue by back2dos** [andyli/hxAnonCls#1]
Saw this in another thread and I was wondering about good ways to let the anonymous class access the inner context.

Have you considered to inject anonymous functions for every method defined?

```
var foo:Int = 5;
typingArea.addKeyListener(AnonCls.make((new KeyListener():{
    public function keyTyped(e) trace(foo);
    //...
})));

//generated once per interface:
class KeyListenerShell implements KeyListener {
    var implementations:{
        keyTyped:KeyEvent->Void;
        //...
    }
    public function new(implementations) {
        this.implementations = implementations;
    }
    public function keyTyped(e) this.implementations.keyTyped(e);
    //...
}
```

This all becomes:

```
var foo:Int = 5;
typingArea.addKeyListener({
    function keyTyped(e) trace(foo);//declaring this here so that other methods of the inner class have it in scope
    //...
    new KeyListenerShell({
        keyTyped: keyTyped, //inject!
        //...
    });
});
```

It would also overcome import/using issues and so on. Of course it's not the best approach for performance critical situations. But it just crossed my mind and I thought you might be interested ;)

**Comment by andyli** [comment]
Yeah, I've thought of that.
The tricky part is that the methods may use `this`, or even reference things from superclass.
But I agree it has potential to become a solid solution, despite of its performance penalty.
I will toy around the idea more. Thanks for bringing this up ;)

**Comment by andyli** [comment]
With the recent commits, hxAnonCls is now able to access the enclosing class instance and local variables. There are still some minor issues, which I will document them next week.
