### ISSUE TITLE
"Invalid call" error at compile time

### ISSUE THREAD

**Issue by mikicho** [andyli/hxAnonCls#2]
Hey,
I have an error when I'm trying to compile this important lib:
```
E:\haxe\haxe\std/Lambda.hx:142: characters 12-14 : Invalid call
hxAnonCls/Macros.hx:334: characters 9-82 : Called from
E:\haxe\haxe\std/neko/_std/Array.hx:275: characters 12-18 : Called from
hxAnonCls/Macros.hx:467: characters 14-37 : Called from
E:\haxe\haxe\std/neko/_std/Array.hx:275: characters 12-18 : Called from
hxAnonCls/Macros.hx:467: characters 14-37 : Called from
hxAnonCls/Macros.hx:573: characters 9-28 : Called from
hxAnonCls/Macros.hx:88: characters 7-26 : Called from
hxAnonCls/AnonCls.hx:371: characters 18-55 : Called from
test/Test.hx:50: lines 50-53 : Called from
Aborted
```

Talked with you about this error about month ago, and now have some time to digging little in the code, it's looks like it have broken by this comment:
https://github.com/HaxeFoundation/haxe/commit/e43164082dac114fb1fbfd05f1e385f88bc866e0

I think we need change this:
``` haxe
if ((untyped v.meta:Metadata).exists(function(m) return m.name == ":unbound"))
```
to this:
``` haxe
if (v.meta.get().exists(function(m) return m.name == ":unbound"))
```
but I'm new with Macros so maybe this wrong,
waiting for your approval :)
Michael

P.s: I opened a post in the mailing list:
https://groups.google.com/forum/#!topic/haxelang/XUrp0zHZXRo

**Comment by andyli** [comment]
Thanks for investigating it! Yeah, your fix is right. I've applied it in 37ca8358a82c086ed5495bb286bb909550862cd5 together with another fix regarding to some Haxe internal change to package.
