### ISSUE TITLE
buildAll not working?

### ISSUE THREAD

**Issue by mikicho** [andyli/hxAnonCls#3]
It's me again :)
Thier is an option that `--macro "hxAnonCls.Macros.buildAll()"` not working?
when I put this line in *my* build.hxml file I get this:
> src/MainActivity.hx:44: lines 44-56 : Expression not allowed here
> src/MainActivity.hx:44: lines 44-56 : For function argument 'param1'

With `@:build(hxAnonCls.Macros.build())` it works like a charm...

**Comment by andyli** [comment]
Umm... It works for me.
Can you create a minimal project that `buildAll()` doesn't work?

**Comment by mikicho** [comment]
I'm suspect that it's related to a java-lib option that I have in my hxml, I'm closing it now, and will open it after I'll finish my little project that will let us create a simple example of the problem.

**Comment by mikicho** [comment]
Just stumbleupon this: https://github.com/andyli/hxAnonCls/commit/e7f4bde30378f111be9e6e6cd9bb3f237d67f78d
Maybe this is why it's not working? :)

**Comment by andyli** [comment]
No, https://github.com/andyli/hxAnonCls/commit/e7f4bde30378f111be9e6e6cd9bb3f237d67f78d only comment out buildAll in the test.hxml. The buildAll feature itself was not removed.

There must be something else that prevents hxAnonCls from processing your class.
